name: mvg
favicon: null
layout_spectrum: 0.25350635568611324
typography_spectrum: 0.1513590356335044
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7244735991116613
  lightness: 0.319891179446131
  saturation: 0.4652474627364427
  rhythmicContrast: 0.42846057028509676
purpose: []
